// And bn.js new BN() weirdly doesn't work with truffle-assertions
const toBN = a => a;
const toBNHex = a => a;


// Configfuration for our tokens

const NUM_EGGS = 3;
const EGG_HATCHING_DELAY = 60;
const NUM_ACCESSORIES = 6;
const MINT_INITIAL_SUPPLY = 1000;
const INITIAL_SUPPLY = toBNHex('0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF');

const CLASS_COMMON = 0;
const CLASS_RARE = 1;
const CLASS_EPIC = 2;
const CLASS_LEGENDARY = 3;
const CLASS_DIVINE = 4;
const CLASS_HIDDEN = 5;
const CLASS_S = 6;
const CLASS_SS = 7;
const NUM_CLASSES = 8;

const LOOTBOX_OPTION_BRONZE = toBN(0);
const LOOTBOX_OPTION_SILVER = toBN(1);
const LOOTBOX_OPTION_GOLD = toBN(2);
const LOOTBOX_OPTION_PLATINUM = toBN(3);
const LOOTBOX_OPTION_DIAMOND = toBN(4);
const LOOTBOX_OPTION_NORMAL1 = toBN(5);
const LOOTBOX_OPTION_NORMAL2 = toBN(6);
const LOOTBOX_OPTIONS = [
  LOOTBOX_OPTION_BRONZE,
  LOOTBOX_OPTION_SILVER,
  LOOTBOX_OPTION_GOLD,
  LOOTBOX_OPTION_PLATINUM,
  LOOTBOX_OPTION_DIAMOND,
  LOOTBOX_OPTION_NORMAL1,
  LOOTBOX_OPTION_NORMAL2
];
const NUM_LOOTBOX_OPTIONS = LOOTBOX_OPTIONS.length;

const NUM_WEAPON_OPTIONS = 9;

const NO_SUCH_LOOTBOX_OPTION = toBN(NUM_LOOTBOX_OPTIONS + 10);
const LOOTBOX_OPTION_AMOUNTS = [toBN(3), toBN(5), toBN(7)];
// Note that these are token IDs, not option IDs, so they are one higher
const LOOTBOX_OPTION_GUARANTEES = [
  {},
  { 0: toBN(3) },
  { 0: toBN(3), 2: toBN(2), 4: toBN(1) }
];

const USDT_ADDRESS = "0xde3A24028580884448a5397872046a019649b084";
const FEE_RECEIVER = "0xB03C52C465F0Fb2A7229A70C5a1D79d6c30162B0";

module.exports = {
  NUM_EGGS,
  EGG_HATCHING_DELAY,
  NUM_ACCESSORIES,
  MINT_INITIAL_SUPPLY,
  INITIAL_SUPPLY,
  CLASS_COMMON,
  CLASS_RARE,
  CLASS_EPIC,
  CLASS_LEGENDARY,
  CLASS_DIVINE,
  CLASS_HIDDEN,
  NUM_CLASSES,
  NUM_WEAPON_OPTIONS,
  LOOTBOX_OPTION_BRONZE,
  LOOTBOX_OPTION_SILVER,
  LOOTBOX_OPTION_GOLD,
  LOOTBOX_OPTION_PLATINUM,
  LOOTBOX_OPTION_DIAMOND,
  LOOTBOX_OPTION_NORMAL1,
  LOOTBOX_OPTION_NORMAL2,
  LOOTBOX_OPTIONS,
  NUM_LOOTBOX_OPTIONS,
  NO_SUCH_LOOTBOX_OPTION,
  LOOTBOX_OPTION_AMOUNTS,
  LOOTBOX_OPTION_GUARANTEES,
  USDT_ADDRESS,
  FEE_RECEIVER,
};
